import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {MockAuthProvider} from "@/app/context/MockAuthProvider";
import Script from "next/script";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CBOT_SRC = 'UPDATE_HERE'

export default function RootLayout({children}: Readonly<{ children: React.ReactNode}>) {
  return (
    <html lang="en">
    <head>
      <title>Hi there!</title>
    </head>
    <body className={inter.className}>
    <MockAuthProvider>
      <Script
        src={CBOT_SRC}
        id={'cbot-widget-script'}
        type="text/javascript"
        async={true}
        data-user={''}
      />
      {children}
    </MockAuthProvider>
    </body>
    </html>
  );
}
